// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseFirst.Contexts;
using DatabaseFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DatabaseFirst.Contexts.Configurations
{
    public partial class StudCourseGradeConfiguration : IEntityTypeConfiguration<StudCourseGrade>
    {
        public void Configure(EntityTypeBuilder<StudCourseGrade> entity)
        {
            entity.ToView("StudCourseGrade");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<StudCourseGrade> entity);
    }
}
