// <auto-generated />
using System;
using Demo.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inheritance_Mapping.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20250927191732_TBT")]
    partial class TBT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inheritance_Mapping.Models.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("age")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Employees");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Inheritance_Mapping.Models.FullTimeEmployee", b =>
                {
                    b.HasBaseType("Inheritance_Mapping.Models.Employee");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.ToTable("FullTimeEmployee", (string)null);
                });

            modelBuilder.Entity("Inheritance_Mapping.Models.PartTimeEmployee", b =>
                {
                    b.HasBaseType("Inheritance_Mapping.Models.Employee");

                    b.Property<decimal>("HourRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HoursWorked")
                        .HasColumnType("int");

                    b.ToTable("PartTimeEmployee", (string)null);
                });

            modelBuilder.Entity("Inheritance_Mapping.Models.FullTimeEmployee", b =>
                {
                    b.HasOne("Inheritance_Mapping.Models.Employee", null)
                        .WithOne()
                        .HasForeignKey("Inheritance_Mapping.Models.FullTimeEmployee", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inheritance_Mapping.Models.PartTimeEmployee", b =>
                {
                    b.HasOne("Inheritance_Mapping.Models.Employee", null)
                        .WithOne()
                        .HasForeignKey("Inheritance_Mapping.Models.PartTimeEmployee", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
