// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DatabaseFirst.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DatabaseFirst.Contexts
{
    public partial interface IITIContextProcedures
    {
        Task<int> Sp_AssignStud2CourAsync(int? stId, int? crsId, int? grade, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
